class Solution {
               public int[][] insert(int[][] intervals, int[] newInterval) {
                          List<int[]> res = new ArrayList<>();
                                     int idx = 0;

                                                // newInterval이 결과 리스트에 이미 추가(병합 완료)되었는지를 추적하는 플래그
                                                           boolean merged = false;

                                                                      while (idx < intervals.length) {
                                                                                     int[] curInterval = intervals[idx];

                                                                                                    // Case 1: curInterval이 newInterval보다 완전히 왼쪽에 있음 (겹치지 않음)
                                                                                                                   if (curInterval[1] < newInterval[0]) {
                                                                                                                                      res.add(curInterval);
                                                                                                                                                         idx++; // 무한 루프 방지를 위해 포인터 증가
                                                                                                                                                                        }
                                                                                                                                                                                       // Case 2: curInterval이 newInterval보다 완전히 오른쪽에 있음 (겹치지 않음)
                                                                                                                                                                                                      else if (curInterval[0] > newInterval[1]) {
                                                                                                                                                                                                                         // 아직 newInterval이 추가되지 않았다면, curInterval을 넣기 전에 먼저 넣어줍니다.
                                                                                                                                                                                                                                            if (!merged) {
                                                                                                                                                                                                                                                                   res.add(newInterval);
                                                                                                                                                                                                                                                                                          merged = true;
                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                res.add(curInterval);
                                                                                                                                                                                                                                                                                                                                                   idx++;
                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                 // Case 3: 두 구간이 겹침 -> newInterval을 계속 업데이트하여 병합을 진행
                                                                                                                                                                                                                                                                                                                                                                                                else {
                                                                                                                                                                                                                                                                                                                                                                                                                   newInterval[0] = Math.min(newInterval[0], curInterval[0]);
                                                                                                                                                                                                                                                                                                                                                                                                                                      newInterval[1] = Math.max(newInterval[1], curInterval[1]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                         idx++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // 루프가 끝났는데도 아직 newInterval이 추가되지 않았다면 (예: 가장 오른쪽에 들어갈 경우)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (!merged) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.add(newInterval);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return res.toArray(new int[res.size()][]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
