class Solution {
        public String minWindow(String s, String t) {
                if (t.isEmpty()) return "";

                        Map<Character, Integer> countT = new HashMap<>();
                                Map<Character, Integer> window = new HashMap<>();

                                        for (char c : t.toCharArray()) {
                                                    countT.put(c, countT.getOrDefault(c, 0) + 1);
                                                            }

                                                                    int have = 0, need = countT.size();
                                                                            int resLen = Integer.MAX_VALUE;
                                                                                    int[] res = {-1, -1};

                                                                                            int l = 0;
                                                                                                    while (l < s.length() && !countT.containsKey(s.charAt(l))) {
                                                                                                                l++;
                                                                                                                        }

                                                                                                                                for (int r = l; r < s.length(); r++) {
                                                                                                                                            char c = s.charAt(r);

                                                                                                                                                        if (countT.containsKey(c)) {
                                                                                                                                                                        window.put(c, window.getOrDefault(c, 0) + 1);

                                                                                                                                                                                        if (window.get(c).equals(countT.get(c))) {
                                                                                                                                                                                                            have++;
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                    while (have == need) {
                                                                                                                                                                                                                                                                    if (r - l + 1 < resLen) {
                                                                                                                                                                                                                                                                                        resLen = r - l + 1;
                                                                                                                                                                                                                                                                                                            res[0] = l;
                                                                                                                                                                                                                                                                                                                                res[1] = r;
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                char leftChar = s.charAt(l);

                                                                                                                                                                                                                                                                                                                                                                                if (countT.containsKey(leftChar)) {
                                                                                                                                                                                                                                                                                                                                                                                                    window.put(leftChar, window.get(leftChar) - 1);

                                                                                                                                                                                                                                                                                                                                                                                                                        if (window.get(leftChar) < countT.get(leftChar)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                have--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    l++;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    while (l < s.length() && !countT.containsKey(s.charAt(l))) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        l++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return resLen == Integer.MAX_VALUE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ? ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : s.substring(res[0], res[1] + 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
}