 
  class Solution {
       public String foreignDictionary(String[] words) {
        
                 int[] indegree = new int[26];
                          Set<Character> chars = new HashSet<>();
                                   Map<Character, Set<Character>> adj = new HashMap<>();
                                    
                                             for (String word : words) {
                                                          for (char c : word.toCharArray()) {
                                                                           chars.add(c);
                                                                                        }
                                                                                                 }
                                                                                                  
                                                                                                           for (int i = 0; i < words.length - 1; i++) {
                                                                                                                        String s1 = words[i];
                                                                                                                                     String s2 = words[i + 1];
                                                                                                                                      
                                                                                                                                                   if (s1.length() > s2.length() && s1.startsWith(s2)) return "";
                                                                                                                                                                for (int j = 0; j < Math.min(s1.length(), s2.length()); j++) {
                                                                                                                                                                                 if (s1.charAt(j) != s2.charAt(j)) {
                                                                                                                                                                                                      char from = s1.charAt(j);
                                                                                                                                                                                                                           char to = s2.charAt(j);
                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                 if (adj.computeIfAbsent(from, a -> new HashSet<>()).add(to)) {
                                                                                                                                                                                                                                                                          indegree[to - 'a']++;
                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                     Queue<Character> que = new LinkedList<>();
                                                                                                                                                                                                                                                                                                                                                                              for (char c : chars) {
                                                                                                                                                                                                                                                                                                                                                                                           if (indegree[c - 'a'] == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                            que.offer(c);
                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                            StringBuilder sb = new StringBuilder();
                                                                                                                                                                                                                                                                                                                                                                                                                                                     while (!que.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  char cur = que.poll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               sb.append(cur);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             for (char next : adj.getOrDefault(cur, Collections.emptySet())) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              int nextInt = next - 'a';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               indegree[nextInt]--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (indegree[nextInt] == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     que.offer(next);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return sb.length() == chars.size() ? sb.toString() : "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
