 class Node {
         int key;
              int val;
                   Node next;
                        Node prev;
                         
                              public Node(int key, int val) {
                                       this.key = key;
                                                this.val = val;
                                                     }
                                                      }
                                                       
                                                        
                                                         class LRUCache {
                                                              Map<Integer, Node> keyToNodeMap = new HashMap<>();
                                                                   int capacity;
                                                                        Node left, right;
                                                                         
                                                                              public LRUCache(int capacity) {
                                                                                       this.capacity = capacity;
                                                                                        
                                                                                                 left = new Node(0, 0);   // dummy head: LRU side
                                                                                                          right = new Node(0, 0);  // dummy tail: MRU side
                                                                                                           
                                                                                                                    left.next = right;
                                                                                                                             right.prev = left;
                                                                                                                                  }
                                                                                                                                   
                                                                                                                                    
                                                                                                                                         public int get(int key) {
                                                                                                                                                  if (!keyToNodeMap.containsKey(key)) return -1;
                                                                                                                                                           Node cur = keyToNodeMap.get(key);
                                                                                                                                                            
                                                                                                                                                                     cur.next.prev = cur.prev;
                                                                                                                                                                              cur.prev.next = cur.next;
                                                                                                                                                                               
                                                                                                                                                                                        right.prev.next = cur;
                                                                                                                                                                                                 cur.prev = right.prev;
                                                                                                                                                                                                          cur.next = right;
                                                                                                                                                                                                                   right.prev = cur;
                                                                                                                                                                                                                    
                                                                                                                                                                                                                             return cur.val;
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                        public void put(int key, int value) {
                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                  if (!keyToNodeMap.containsKey(key)) {
                                                                                                                                                                                                                                                               Node node = new Node(key, value);
                                                                                                                                                                                                                                                                            right.prev.next = node;
                                                                                                                                                                                                                                                                                         node.prev = right.prev;
                                                                                                                                                                                                                                                                                                      node.next = right;
                                                                                                                                                                                                                                                                                                                   right.prev = node;
                                                                                                                                                                                                                                                                                                                                keyToNodeMap.put(key, node);
                                                                                                                                                                                                                                                                                                                                         } else {
                                                                                                                                                                                                                                                                                                                                                      Node cur = keyToNodeMap.get(key);
                                                                                                                                                                                                                                                                                                                                                                   cur.val = value;
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                 cur.next.prev = cur.prev;
                                                                                                                                                                                                                                                                                                                                                                                              cur.prev.next = cur.next;
                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                            right.prev.next = cur;
                                                                                                                                                                                                                                                                                                                                                                                                                         cur.prev = right.prev;
                                                                                                                                                                                                                                                                                                                                                                                                                                      cur.next = right;
                                                                                                                                                                                                                                                                                                                                                                                                                                                   right.prev = cur;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (keyToNodeMap.size() > capacity) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Node lru = keyToNodeMap.remove(left.next.key);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               lru.next.prev = lru.prev;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            lru.prev.next = lru.next;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

 